#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-bash_kernel
Version  : 0.8.0
Release  : 9
URL      : https://files.pythonhosted.org/packages/d9/2b/0f98098108aa7fa2c18d245e380d15b585e65a8c0f07b2fc11e1d1fe3b7f/bash_kernel-0.8.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/d9/2b/0f98098108aa7fa2c18d245e380d15b585e65a8c0f07b2fc11e1d1fe3b7f/bash_kernel-0.8.0.tar.gz
Summary  : A bash kernel for Jupyter
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-bash_kernel-license = %{version}-%{release}
Requires: pypi-bash_kernel-python = %{version}-%{release}
Requires: pypi-bash_kernel-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(flit_core)
BuildRequires : pypi(ipykernel)

%description
A Jupyter kernel for bash
This requires IPython 3.
To install::
pip install bash_kernel
python -m bash_kernel.install

%package license
Summary: license components for the pypi-bash_kernel package.
Group: Default

%description license
license components for the pypi-bash_kernel package.


%package python
Summary: python components for the pypi-bash_kernel package.
Group: Default
Requires: pypi-bash_kernel-python3 = %{version}-%{release}

%description python
python components for the pypi-bash_kernel package.


%package python3
Summary: python3 components for the pypi-bash_kernel package.
Group: Default
Requires: python3-core
Provides: pypi(bash_kernel)
Requires: pypi(ipykernel)
Requires: pypi(pexpect)

%description python3
python3 components for the pypi-bash_kernel package.


%prep
%setup -q -n bash_kernel-0.8.0
cd %{_builddir}/bash_kernel-0.8.0
pushd ..
cp -a bash_kernel-0.8.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1661192267
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-bash_kernel
cp %{_builddir}/bash_kernel-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-bash_kernel/76c7e710d472be20ce886472767e77a7d52692b8
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-bash_kernel/76c7e710d472be20ce886472767e77a7d52692b8

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
